/* Local fixture checks for themed controls and bounded chart layout. */
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const file=path.join(__dirname,'browser.cjs');let src=fs.readFileSync(file,'utf8');src=src.slice(0,src.lastIndexOf('\nrun().catch'))+'\nmodule.exports={setup,server,report};';const m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(__dirname);m._compile(src,file);const{setup,server,report}=m.exports;
const out=process.env.TEST_OUTPUT||path.join(__dirname,'artifacts','controls');fs.mkdirSync(out,{recursive:true});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,b=await chromium.launch({channel:'chrome',headless:true}),ctx=await b.newContext({reducedMotion:'reduce',timezoneId:'America/New_York'});await ctx.route('**/*',r=>r.request().url().startsWith(base)?r.continue():(report.externalRequests.push(r.request().url()),r.abort()));const checks=[];
for(const theme of ['light','dark'])for(const width of [1280,390]){
 const p=await ctx.newPage();await p.setViewportSize({width,height:900});await setup(p,{theme,lang:'zh',state:'empty'});await p.goto(base+'/heatmap.html');await p.locator('#yearSelectControl').waitFor();await p.locator('#tab-usage').click();await p.waitForTimeout(120);
 const panel=await p.locator('#usagePanel').boundingBox(),badge=await p.locator('#proTrust').boundingBox();assert.ok(badge.x+badge.width<=panel.x+panel.width);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 // Custom selector commits through the existing field, including keyboard selection.
 await p.evaluate(()=>{const s=document.getElementById('yearSelect');s.add(new Option('2025','2025'));});await p.locator('#yearSelectControl').click();await p.keyboard.press('End');await p.keyboard.press('Enter');assert.equal(await p.locator('#yearSelect').inputValue(),'2025');
 await p.locator('#membership').evaluate(e=>{for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});await p.locator('#membershipControl').click();await p.locator('.control-option').filter({hasText:'Business Premium'}).click();await p.waitForFunction(()=>!document.getElementById('calReset').disabled);await p.locator('.advanced-panel').evaluate(e=>e.open=false);
 await p.locator('#calibrateDetails').evaluate(e=>e.open=true);await p.locator('#calReset').fill('2027-06-15T13:45');
 await p.locator('#calResetControl').click();await p.locator('[data-action=next]').click();await p.locator('.calendar-actions .cancel').click();assert.equal(await p.locator('#calReset').inputValue(),'2027-06-15T13:45');
 await p.locator('#calResetControl').click();await p.keyboard.press('Escape');assert.equal(await p.locator('#calResetControl').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('#calReset').inputValue(),'2027-06-15T13:45');
 await p.locator('#calResetControl').click();await p.locator('.calendar-time input').first().fill('25');await p.locator('.calendar-actions .apply').click();assert.equal(await p.locator('.date-popover').count(),1);assert.equal(await p.locator('#calReset').inputValue(),'2027-06-15T13:45');
 await p.locator('.calendar-time input').first().fill('14');await p.locator('.calendar-time input').last().fill('05');await p.locator('.calendar-actions .apply').click();assert.equal(await p.locator('#calReset').inputValue(),'2027-06-15T14:05');
 await p.locator('#calResetControl').click();const bounds=await p.locator('.date-popover').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y>=0&&bounds.y+bounds.height<=900);await p.locator('.date-popover').screenshot({path:path.join(out,`calendar-${theme}-${width}.png`)});await p.locator('.calendar-actions .clear').click();assert.equal(await p.locator('#calReset').inputValue(),'');
 await p.locator('#calibrateDetails').screenshot({path:path.join(out,`form-${theme}-${width}.png`)});await p.locator('#yearSelectControl').click();await p.locator('#control-popup').screenshot({path:path.join(out,`select-${theme}-${width}.png`)});await p.keyboard.press('Escape');
 await p.locator('#tab-activity').click();await p.waitForTimeout(100);assert.equal(await p.locator('#monthlyTotals button').count(),12);assert.equal(await p.locator('#weeklyTotals button').count(),0);
 await p.evaluate(()=>renderSummaryColumns(document.getElementById('weeklyTotals'),Array.from({length:53},(_,i)=>({total:i,label:String(i+1),full:'Week '+(i+1)})),'weekly'));
 assert.equal(await p.locator('#weeklyTotals button').count(),53);await p.locator('#weeklyTotals button').first().focus();await p.keyboard.press('End');assert.equal(await p.locator('#weeklyTotals button').last().evaluate(e=>e===document.activeElement),true);assert.ok(await p.locator('#weeklyTotals').evaluate(e=>e.parentElement.scrollLeft>0));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok((await p.locator('.trend-summary .summary-block').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).every(h=>h===292));
 checks.push({theme,width,emptyLayout:true,keyboardSelect:true,cancelEscapeClear:true,invalidTime:true,localTime:true,popoverBounds:bounds,fullYearChart:true});await p.close();
}
assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);fs.writeFileSync(path.join(out,'controls-report.json'),JSON.stringify({checks,errors:report.errors,externalRequests:report.externalRequests},null,2));console.log('4 theme/viewport edge-case suites passed');await b.close();server.close();})().catch(e=>{console.error(e);server.close();setTimeout(()=>process.exit(1),500);});
