/* Behavior regressions for dynamic labels, saved usage, and compact charts. Local fixtures only. */
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const source=path.join(__dirname,'browser.cjs');let code=fs.readFileSync(source,'utf8');
code=code.slice(0,code.lastIndexOf('\nrun().catch'))+'\nmodule.exports={setup,server,report};';
const harness=new Module(source,module);harness.filename=source;harness.paths=Module._nodeModulePaths(__dirname);harness._compile(code,source);
const {setup,server,report}=harness.exports;
const out=process.env.TEST_OUTPUT||path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({reducedMotion:'reduce'});const checks=[];
 await ctx.route('**/*',r=>r.request().url().startsWith(base)?r.continue():(report.externalRequests.push(r.request().url()),r.abort()));
 for(const lang of ['en','zh']){
  const p=await ctx.newPage();await p.setViewportSize({width:390,height:844});await setup(p,{theme:'light',lang,state:'error'});await p.goto(base+'/heatmap.html');
  await p.waitForFunction(()=>document.getElementById('overviewProTitle').textContent===GPTTrackerI18n.t('pro_recorded_title'));
  assert.equal(await p.locator('#overviewPro').textContent(),'5');
  assert.match(await p.locator('#overviewCacheNote').textContent(),lang==='zh'?/刷新失败[\s\S]*更新于/:/Refresh failed[\s\S]*Updated/);
  checks.push(lang+': local Pro label and visible cached timestamp');
  await p.locator('#tab-usage').click();await p.locator('#calibrateDetails').evaluate(n=>n.open=true);await p.locator('#calRemaining').fill('40');await p.locator('#calReset').fill('2027-01-01T12:00');await p.locator('#calSave').click();
  await p.waitForFunction(()=>fixture.state.settings[GPTUsageCore.LOCAL_SCOPE]?.baselines?.shared_week?.used===10);
  await p.locator('#tab-overview').click();await p.waitForFunction(()=>document.getElementById('overviewProTitle').textContent===GPTTrackerI18n.t('pro_estimated_title'));
  assert.match(await p.locator('#overviewPro').textContent(),/40/);
  await p.locator('#tab-usage').click();await p.locator('#calClear').click();await p.waitForFunction(()=>!fixture.state.settings[GPTUsageCore.LOCAL_SCOPE].baselines.shared_week);
  assert.equal(await p.locator('#usageCacheNote').isVisible(),true);
  await p.locator('#tab-overview').click();await p.waitForFunction(()=>document.getElementById('overviewProTitle').textContent===GPTTrackerI18n.t('pro_recorded_title'));
  checks.push(lang+': calibration and clear change the title with the value');
  await p.locator('#tab-activity').click();await p.waitForFunction(()=>document.getElementById('heatmapScroll').scrollLeft>0);
  assert.equal(await p.locator('#heatmapNavigation').isVisible(),true);
  assert.equal(await p.evaluate(()=>{const b=document.getElementById('heatmapScroll').getBoundingClientRect(),c=document.querySelector('[data-date="'+toISODate(new Date())+'"]').getBoundingClientRect();return c.left>=b.left&&c.right<=b.right;}),true);
  await p.evaluate(()=>{document.getElementById('heatmapScroll').scrollLeft=0;renderCalendar(currentYear);});await p.waitForTimeout(60);
  assert.equal(await p.locator('#heatmapScroll').evaluate(n=>n.scrollLeft),0);
  await p.locator('#heatmapCurrent').click();await p.waitForFunction(()=>document.getElementById('heatmapScroll').scrollLeft>0);
  checks.push(lang+': current month visible, manual scroll retained, recenter works');
  assert.equal(await p.locator('#distributionLegend li').count(),6);
  assert.equal(await p.evaluate(()=>timeDistributionState.total),28);
  await p.evaluate(()=>{allData['2020-01-01']={count:100,timestamps:[]};updateTimeDistribution();});assert.equal(await p.evaluate(()=>timeDistributionState.total),28);
  assert.equal(await p.locator('#timePieChart').getAttribute('role'),'img');
  await p.screenshot({path:path.join(out,'readability-'+lang+'-activity.png'),fullPage:true});
  checks.push(lang+': six legend entries and timestamp-only denominator');
  await p.evaluate(()=>{allData={};renderCalendar(currentYear);updateDailyChartForToday();updateTimeDistribution();});
  assert.equal(await p.locator('#timePieChart').isVisible(),false);
  assert.equal(await p.locator('#dailyEmpty').isVisible(),true);
  assert.ok((await p.locator('#timeDistributionSection').boundingBox()).height<250);
  assert.ok((await p.locator('.daily-chart-wrapper').boundingBox()).height<180);
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await p.screenshot({path:path.join(out,'readability-'+lang+'-empty.png'),fullPage:true});
  checks.push(lang+': empty charts collapse without horizontal overflow');await p.close();
  const pop=await ctx.newPage();await pop.setViewportSize({width:338,height:600});await setup(pop,{theme:'light',lang,state:'error'});await pop.goto(base+'/popup.html');await pop.waitForSelector('#popupCacheNote');
  const fits=await pop.evaluate(()=>{const n=document.getElementById('popupCacheNote'),b=n.closest('.card').getBoundingClientRect(),a=n.getBoundingClientRect(),bar=document.getElementById('codexProgress').getBoundingClientRect();return a.left>=b.left&&a.right<=b.right&&a.bottom<=b.bottom&&a.top>=bar.bottom&&n.scrollHeight<=n.clientHeight+1;});
  assert.equal(fits,true,'cached notice fits the Popup card');
  await pop.screenshot({path:path.join(out,'readability-'+lang+'-popup-error.png')});
  await pop.evaluate(()=>{fixture.error=null;fixture.live.updatedAt=Date.now();fixture.emit();});
  await pop.waitForFunction(()=>document.getElementById('popupCacheNote').hidden);
  assert.equal(await pop.locator('.codex .reset').isVisible(),true);
  checks.push(lang+': Popup cached notice fits and clears on recovery');await pop.close();
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);
 fs.writeFileSync(path.join(out,'readability-report.json'),JSON.stringify({checks,errors:report.errors,externalRequests:report.externalRequests},null,2));
 console.log(checks.length+' readability checks passed');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();setTimeout(()=>process.exit(1),500);});
