'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),C=require('../usage-core');
const response=v=>({ok:true,json:async()=>v});
const usage={plan_type:'pro',rate_limit:{primary_window:{used_percent:1,limit_window_seconds:10800}}};
function harness({tabs=[{id:1,active:true}],capture=async()=>{throw Error('no receiver');},fetcher,seed={},fast=false}={}){
 const data=structuredClone(seed),calls=[],messages=[];let listener;
 const chrome={runtime:{id:'test',getURL:s=>'chrome-extension://test/'+s,onMessage:{addListener:f=>listener=f},onInstalled:{addListener(){}},onStartup:{addListener(){}}},storage:{local:{setAccessLevel:async()=>{},get:async k=>k===null?structuredClone(data):Object.fromEntries((Array.isArray(k)?k:[k]).map(x=>[x,data[x]])),set:async v=>Object.assign(data,structuredClone(v))}},tabs:{query:async()=>tabs,sendMessage:async(id,m)=>{messages.push(m);return capture(id,m);}}};
 const ctx={chrome,GPTUsageCore:C,URL,AbortController,console,importScripts(){},setTimeout:fast?(f,ms)=>setTimeout(f,ms>=10000?5:ms):setTimeout,clearTimeout,fetch:async(url,o)=>{calls.push({url,...o});return fetcher?fetcher(url,o):response(url.endsWith('/session')?{accessToken:'FAKE_LOCAL_TOKEN'}:usage);}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../background.js'),'utf8'),ctx);
 return {data,calls,messages,request:(type='UG_REFRESH_LIVE')=>new Promise(resolve=>listener({type},{id:'test',url:type==='UG_POLL_LIVE'?'https://chatgpt.com/c/test':'chrome-extension://test/popup.html',...(type==='UG_POLL_LIVE'?{tab:{id:1}}:{})},resolve))};
}
test('missing bridge automatically reads session then usage, with GET only and no persisted token',async()=>{const h=harness({seed:{'2026-09-01':{count:4}}});const r=await h.request();assert.equal(r.refreshed,true);assert.equal(h.calls.length,2);assert.ok(h.calls[0].url.endsWith('/api/auth/session'));assert.ok(h.calls[1].url.endsWith('/backend-api/wham/usage'));assert.ok(h.calls.every(c=>c.method==='GET'&&c.credentials==='include'&&c.redirect==='error'&&!c.body));assert.equal(h.calls[1].headers.authorization,'Bearer FAKE_LOCAL_TOKEN');assert.ok(!JSON.stringify(h.data).includes('FAKE_LOCAL_TOKEN'));assert.equal(h.data.__gptLiveUsageV1.meters[0].remainingPercent,99);assert.equal(h.data['2026-09-01'].count,4);});
test('no open ChatGPT tabs can refresh without creating or reloading a tab',async()=>{const h=harness({tabs:[]});assert.equal((await h.request()).refreshed,true);assert.equal(h.messages.length,0);});
test('old hidden bridge falls back on manual refresh; automatic polling remains paused',async()=>{const h=harness({capture:async()=>({ok:false,status:'hidden'})});assert.equal((await h.request('UG_POLL_LIVE')).status,'hidden');assert.equal(h.calls.length,0);assert.equal((await h.request()).refreshed,true);assert.equal(h.messages.at(-1).manual,true);});
test('healthy page bridge is preferred without duplicate background network calls',async()=>{const h=harness({capture:async()=>({ok:true,status:'ok'})});assert.equal((await h.request()).refreshed,true);assert.equal(h.calls.length,0);});
test('multiple UI refresh requests share one complete fallback chain',async()=>{const h=harness({fetcher:async url=>{await new Promise(r=>setTimeout(r,5));return response(url.endsWith('/session')?{accessToken:'FAKE'}:usage);}});const r=await Promise.all([h.request(),h.request(),h.request()]);assert.ok(r.every(x=>x.refreshed));assert.equal(h.calls.length,2);});
test('missing login stops before usage fetch and retains the old snapshot',async()=>{const prior={updatedAt:Date.now()-600000,plan:'pro_unknown',meters:[]},h=harness({seed:{__gptLiveUsageV1:prior},fetcher:async()=>response({})});assert.equal((await h.request()).status,401);assert.equal(h.calls.length,1);assert.deepEqual(h.data.__gptLiveUsageV1,prior);assert.equal((await h.request()).status,'backoff');assert.equal(h.calls.length,1);});
test('403, 429, network and invalid responses produce explicit bounded failure states',async()=>{for(const expected of [403,429,'network-error','invalid-response']){const h=harness({fetcher:async()=>{if(expected==='network-error')throw Error('offline');if(expected==='invalid-response')return {ok:true,json:async()=>{throw Error('html');}};return {ok:false,status:expected};}});assert.equal((await h.request()).status,expected);assert.equal((await h.request()).status,'backoff');assert.equal(h.calls.length,1);}});
test('10-second fetch timeout is bounded and leaves retry available after backoff',async()=>{const h=harness({fast:true,fetcher:async(_u,o)=>new Promise((_r,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error(),{name:'AbortError'}))))});assert.equal((await h.request()).status,'timeout');assert.equal(h.data.__gptLiveUsageErrorV1.status,'timeout');});
test('stale old bridge token gets one fresh-session fallback, renewed bridge auth error does not loop',async()=>{const old=harness({capture:async()=>({ok:false,status:401})});assert.equal((await old.request()).refreshed,true);const fresh=harness({capture:async()=>({ok:false,status:401,sessionRenewed:true})});assert.equal((await fresh.request()).status,401);assert.equal(fresh.calls.length,0);});
test('unresponsive page bridge times out without a parallel fallback request',async()=>{const h=harness({fast:true,capture:()=>new Promise(()=>{})});assert.equal((await h.request()).status,'timeout');assert.equal(h.calls.length,0);});
test('recent successful reading returns current metadata instead of a false failure',async()=>{const h=harness({seed:{__gptLiveUsageV1:{updatedAt:Date.now(),plan:'pro_unknown',meters:[]}}});const r=await h.request();assert.equal(r.current,true);assert.equal(r.refreshed,false);assert.equal(h.calls.length,0);});
